### PR TITLE
NCrunch v5 Updates

### PR DESCRIPTION
**Pull request by SeanKilleen**
Just too excited to get [the latest v5 edition](https://blog.ncrunch.net/post/NCrunch-V5-Now-Available.aspx), figured I'd try to contribute :)

My process:

* [x] Update the version number in all the Powershell files
* [x] Use Get-FileHash on all the downloaded files to update the checksum32 value in the Powershell 
  * (checked on the prior version to ensure it produced matching values)
* [x] Update the .nuspec files

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@hbre I think this is ready for your review. You may need to enable the workflow to run. Thanks for considering this PR (and for maintaining the package!)

**Comment by SeanKilleen** [comment]
Actually, late breaking change -- looks like v5.1 has been released just today with some fixes that are important enough to update this PR. Going to do that now.

**Comment by SeanKilleen** [comment]
OK, updated to the latest and ready for review.

**Comment by hbre** [comment]
Hi, 

the download url in the website changed so my updater action could not find it. 

I fixed it, the automatic action could find the update and pushed new versions:
https://community.chocolatey.org/packages/ncrunch-vs2022#versionhistory

Thank you for your patch, but i close it as the automation made the update and pushed the packages to chocolatey. Hope that this works again for some year ;) otherwise please ping me and i'll have a look!

Thanks again,
 Henning

**Comment by SeanKilleen** [comment]
Makes perfect sense @hbre  -- thanks for letting me know, and for getting the latest out there!

**Pull request closed without merging**
